name: 強制デプロイ

on:
  workflow_dispatch:

jobs:
  force-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: ファイル取得
      uses: actions/checkout@v3
    
    - name: エックスサーバーに強制アップロード
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./wts/
        server-dir: /public_html/Smiley/taxi/wts/
        state-name: .ftp-deploy-sync-state-force.json
        exclude: |
          **/.git*
          **/README.md
          **/.github/**
